# ~/.bashrc
#
# This file is part of bashrc.x.
#
# bashrc.x is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bashrc.x is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bashrc.x.  If not, see <http://www.gnu.org/licenses/>.
#
# @package   bashrc.x
# @author    Snakevil Zen <zsnakevil@gmail.com>
# @copyright © 2012 szen.in
# @license   http://www.gnu.org/licenses/gpl.html

export __BASHRC_X_CHECKPOINT=(`'date' +%s.%N`, "")

[ -n "$BASH" ] || return

[ -n "$PS1" ] || return

export HISTCONTROL="ignoreboth"
export HISTFILESIZE=840806
export HISTIGNORE="ls:fg:ll:la"
export HISTSIZE=2012
export HISTTIMEFORMAT="%F %T "

shopt -s histappend

set -o functrace
shopt -s extdebug

for _ii_ in $(for _ii_ in ~/.local/bashrc.x/etc/bashrc.d/[0-9][0-9]-*.sh \
    ~/.bashrc.x/bashrc.d/[0-9][0-9]-*.sh; do
    [ ! -r "$_ii_" ] || {
      printf "%-256s" `'basename' "$_ii_"`
      echo "$_ii_"
    }
  done | 'sort' -k'1,1' -k'2r' | 'cut' -b'257-'); do
  . "$_ii_"
done

unset -v _ii_ _jj_ _kk_

# vim: se ft=sh ff=unix fenc=utf-8 sw=2 ts=2 sts=2:
